label a1s3: 
    show bg garden dead 
    a "Here it is… or, what’s left of it."
    v "Damn…Seems pretty bad."
    a "No shit."
    a "I tried keeping it alive, but after a while I just… couldn't keep it going."
    a "But I suppose since you're back…"
    #what is shuffling noise? add that...
    menu: 
        "Pink Camellia (representing longing)": 
            v "Ah, my favorite one. It'll be a nice splash of color to this blank canvas."
            pass
        "Heather flower (representing good fortune)":
            v "Heather… Interesting. I suppose our meeting is good fortune…"
        "Aster flower (representing love)":
            v "Oooh, aster. A bit unconventional, but not like that's a bad thing."
    a "I'll make sure this one blooms."
    a "And then maybe we'll have a full garden again, like we did before."
    v "We will."
    pause(4)
    v "So…! What else’re you planning on doing today?"
    a "I just wanted to ask something really"
    a "Ghosts tend to come back when they have regrets, right? Or unfinished business?"
    a "So…"
    v "I mean…"
    v "We don't exactly have any other spirits to compare me to"
    v "So like…"
    v "Just don't worry about it~♩"
    a "Uh… alright."
    play audio "fast-knocking-on-door-352704.mp3"
    a "Oh, that must be Ryan."
    v "Ryan{cps=*.5}…{/cps}"
    v "Uh… wait, who was this guy again?"
    a "Just a college friend."
    show staircase
    r "Eyy, Alex! Good to see ya again!"
    a "Hi."
    r "Looks like you're doing better."
    a "Yeah, just a little."
    r "Well, in that case…" 
    r "Been up to anything in the past few weeks?"
    v "...Does this dude have any tact?"
    a "I mean, you know what's been goin' on."
    a "If you came here for the garden, I'm sorry to disappoint."
    r "Eh, that's whatever."
    r "Anyway… I've been busy, personally."
    r "Doin' a lot of reading, you see."
    r "Been trying to understand the otherside, as it were."
    v "What?"
    a "What?"
    r "I've been workin' out as well. I haven't gotten much, but it's steady progress."
    a "Oh… that's great."
    a "Uh… Anything else you've been doing?"
    r "Eh, not much aside from that. But I'll be getting someone soon enough, just you wait."
    v "You were friends with this dude?"
    r "And they'll be twice as hot as–"
    a "Good lord, Ryan. Can't you just let bygones be bygones?"
    v "Alex, we might need to kill this dude."
    a "{size=*.5}I wouldn't go that far, but...{/size}"
    r "What was that?"
    a "Nothing."
    r "Sssure…"
    r "Anyway."

